### ISSUE TITLE
Very slow working... 2 polylines + markers

### ISSUE THREAD

**Issue by wikiro** [branflake2267/GWT-Maps-V3-Api#146] opened 2013-02-02 06:39 UTC
Here the example: 
http://wikiroutes.info/updates/22152

Gooogle maps version 2 was very fast. What is the reason? How to increase perfomance?

**Comment by branflake2267** [comment] 2013-02-02 11:37
Do you have some source?

**Comment by wikiro** [comment] 2013-02-02 15:15
If you look at showcase http://gonevertical-apis.appspot.com/  
map: Directions Service, Distance=76,2 км Duration=53 мин.
it works slow too...

**Comment by branflake2267** [comment] 2013-02-02 19:04
I don't see any latency with the directions service in the showcase and if there is it most likely network related. The wrapper merely wraps the direction service with a call and callback and doesn't do anything special so it wouldn't slow it down. The showcase does have many maps loading at once so it might slow it down some but I've never noticed. Can you add some timing output so I could get a feeling for how slow?

**Comment by branflake2267** [comment] 2013-02-02 19:05
I might suggest asking javascript user group to see if anybody has had the same issue?

**Comment by wikiro** [comment] 2013-02-03 15:05
http://wikiroutes.info/spb?routes=674

Zoom map and you will see that markers becomes bigger or smaller and polyline too. It might depend on that maps 3 used canvas. How to disable this? in version maps api 2 they use a < path >  tag

**Comment by branflake2267** [comment] 2013-02-03 17:26
Can you add a screen shot to this to show me what you are seeing specifically. I zoomed in on the map and I see the polyline and markers shrinking on the zoomin. 

![Screen Shot 2013-02-03 at 9 25 35 AM](https://f.cloud.github.com/assets/1326504/122046/e41b2300-6e26-11e2-947a-112795660b19.png)

**Comment by branflake2267** [comment] 2013-02-03 17:28
Cool site! Is that yours and could I add that link to the readme?

**Comment by wikiro** [comment] 2013-02-04 05:54
Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.13

**_zoom in:**_
![in](https://f.cloud.github.com/assets/3327424/122784/3df0c2fa-6e8f-11e2-89c8-2d42f2f15955.jpg)

**_zoom out**_
![out](https://f.cloud.github.com/assets/3327424/122787/4e09042c-6e8f-11e2-8b8b-192b18504f80.jpg)

yes, it's my site, yes you can add, thank you

**Comment by branflake2267** [comment] 2013-02-04 06:01
I tried zooming in and out on chrome and I didn't get missing squares yet.

**Comment by branflake2267** [comment] 2013-02-04 06:04
I'm wondering if you could check the chrome inspector to see if there is any javascript errors in the console?

**Comment by wikiro** [comment] 2013-02-04 06:15
please, try in opera

**Comment by branflake2267** [comment] 2013-02-10 19:01
I don't have control over the rendering in the map since we are just wrapping the javascript methods. I might see what the group might say about this subject:
https://groups.google.com/forum/?fromgroups#!forum/google-maps-js-api-v3

**Comment by twistedpair** [comment] 2013-02-10 23:20
A tip, encode your track at multiple levels. Encoded polylines are made sparser at more zoomed out levels, meaning that the points you cannot see at a given level are not rendered. This is making rendering faster. You can use encoded polylines with the library and the encoding utils.

**Comment by twistedpair** [comment] 2014-01-14 21:40
Closing because it is not apparent that this issue is caused by the GWT-Maps-V3-API wrapper. The issue is likely an artifact of the underlying JS lib based on browser and hardware. As such, it is beyond the scope of this project to fix these issues.

**Closed as completed by twistedpair** 2014-01-14 21:40 UTC
Labels: question, JS API Bug
